### ISSUE TITLE
TypeError: init_registry_client() got an unexpected keyword argument 'registry_server'

### ISSUE THREAD

**Issue by simoneobo** [keijack/python-eureka-client#1]
Hi, i'm trying to use this module in a simple example, but everytime a run the script i obtain this error:
`TypeError: init_registry_client() got an unexpected keyword argument 'registry_server'`

Can you help me?
Thank you

The code is:
```
import py_eureka_client.eureka_client as eureka_client

your_rest_server_port = 9090
eureka_client.init_registry_client(registry_server="http://localhost:8761/eureka",
app_name="your_app_name",
instance_port=your_rest_server_port)
```

**Comment by keijack** [comment]
> Hi, i'm trying to use this module in a simple example, but everytime a run the script i obtain this error:
> `TypeError: init_registry_client() got an unexpected keyword argument 'registry_server'`
> 
> Can you help me?
> Thank you
> 
> The code is:
> 
> ```
> import py_eureka_client.eureka_client as eureka_client
> 
> your_rest_server_port = 9090
> eureka_client.init_registry_client(registry_server="http://localhost:8761/eureka",
> app_name="your_app_name",
> instance_port=your_rest_server_port)
> ```

I'm sorry, that I change the keyword argument name from `registry_server` to `eureka_server`, I have update the README file
