### ISSUE TITLE
404 GET /health

### ISSUE THREAD

**Issue by chasingML** [keijack/python-eureka-client#15]
你好，注册成功之后出现404 GET /health的日志信息，看起来像是在查询服务健康状况？

**Comment by keijack** [comment]
Hi, dear, this component won't setup a HTTP server and provide the health checking REST interface, you should always provide this in your APP.

**Comment by chasingML** [comment]
yeah, but I found a function status_update, it likes providing a health checking REST interface?

**Comment by keijack** [comment]
Hi, dear, this function is for sending the component's status to eureka server, it does not provide a REST interface.

**Comment by chasingML** [comment]
ok, tks
