### ISSUE TITLE
Nonetype returned for eureka_client.do_service() ???

### ISSUE THREAD

**Issue by tyu0912** [keijack/python-eureka-client#17]
Hi, what does it mean when I get `None` when running `eureka_client.do_service` ? The exact code is as below so not sure what could be happening. No errors are produced, the service does exist, and the different VPCs on AWS can talk to each other. 

```
env = os.getenv('xxxxx_EUREKA_SERVICE')
path = "/api/yyyyy/v1/event?xyz=" + some_field

eureka_client.do_service(env, path, method='GET')
```
Thank you.

**Comment by keijack** [comment]
I'm sorry to response so late, what is the `env` in your code? is that a service name register in eureka server? @tyu0912

**Comment by keijack** [comment]
no response for long time.
