### ISSUE TITLE
secureHealthCheckUrl

### ISSUE THREAD

**Issue by peter254** [keijack/python-eureka-client#20]
Hello,
At the moment we are using your library and it works very well! But we are missing one feature - the secureHealthCheckUrl attribute. As far as I understand it, the attribute is read when receiving a service, but I could only find the option to set the normal health check URL.

**Comment by keijack** [comment]
Hi, @peter254 ,
You can find the Nodes via this:

    application_name="YOUR_SERVICE"
    cli = eureka_client.get_discovery_client()
    app = cli.applications.get_application(application_name)
    for ins in app.instances:
        print(ins.healthCheckUrl)
        # you can also find all the properties in this object like vipAddress/statusPageUrl
    # or you can only go through the up instances
    for ins in app.up_instances:
        print(ins.healthCheckUrl)

**Comment by peter254** [comment]
Hey @keijack
I am talking about the Registration, not the discovery - sorry for the misunderstanding

**Comment by keijack** [comment]
@peter254 sorry for response so late. in v 0.7.3， you can use `secure_health_check_url` parameter in `init` method to specify your own secureHealthCheckUrl。
