### ISSUE TITLE
Eureka server [http://localhost:8761/] is down, use next url to try.

### ISSUE THREAD

**Issue by rainkidpk** [keijack/python-eureka-client#22]
Hello, when i use this library, i receive error
" Eureka server [http://localhost:8761/] is down, use next url to try."

when I click on the link above,The path I received was "http://localhost:8761/%5D"
what "%5D",
Is it an error?

pls support

**Comment by keijack** [comment]
Hi, %5D is the encoded character of ] ,  I think it's not the main problem, what's the result if you just curl `http://localhost:8761/`?

**Comment by adventl** [comment]
Hi Keijack, I am getting the same issue as rainkidpk

I have tried using Postman to send a get request to http://localhost:8761/ and got the HTML page in response

**Comment by keijack** [comment]
how about to set the eureka url as `http://localhost:8761/eureka`?

**Comment by DKMDebugin** [comment]
Adding /eureka to the URI worked for me. Thanks
