### ISSUE TITLE
DeprecationWarning: This method will be removed

### ISSUE THREAD

**Issue by dinuta** [keijack/python-eureka-client#23]
Hi man,

I use your eureka connector for multiple services and i keep receiving a deprecating warning.
You can see the log here: https://travis-ci.org/dinuta/netflixoss-eureka/builds/611704241

`/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/py_eureka_client/eureka_client.py:390: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for child_node in xml_node.getchildren():
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/py_eureka_client/eureka_client.py:481: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for child_node in xml_node.getchildren():
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/py_eureka_client/eureka_client.py:474: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for child_node in xml_node.getchildren():
Getting apps from eureka server http://localhost:8081/eureka/v2 ...`

**Comment by keijack** [comment]
@dinuta, thanks. I've replaced that deprecated method to the recommended method. Please upgrade to 0.7.4.

**Comment by dinuta** [comment]
Thanks man,
Looking good on my latest build: https://travis-ci.org/dinuta/netflixoss-eureka/builds/611768354. 
No warnings anymore. 
As you probably saw, i'm using Python 3.7.

I think you can close this one.
