### ISSUE TITLE
Update instance status

### ISSUE THREAD

**Issue by DeAJota** [keijack/python-eureka-client#24]
Hello,

I'm trying update status of my application instance  on eureka but don't work. Debugging I have seen that method status_update on RegistryClient class call status_update function and this have a literal:

`apps/%s/%s?status=%s&lastDirtyTimestamp=%s`

According to this link [https://dzone.com/articles/the-mystery-of-eureka-health-monitoring](url) and this [https://github.com/Netflix/eureka/wiki/Eureka-REST-operations](url) the literal don't seems correct. The correct url should be:

`apps/%s/%s/status?value=%s&lastDirtyTimestamp=%s`

**Comment by keijack** [comment]
resolve, see release 0.7.5
