### ISSUE TITLE
Implement DNS discovery feature

### ISSUE THREAD

**Issue by dethmix** [keijack/python-eureka-client#30]
Hello,
One of the main Eureka's feature is to automatically discover Eureka Servers from the TXT record. Is there any plans to implement it here?
As far as I can currently `useDNS` option isn't support in the lib.
Possibly you can look into implementation of that feature in alternative lib https://github.com/KristianOellegaard/python-eureka (it is old and only for python2 :( )

**Comment by keijack** [comment]
I'll  check it out.

**Comment by keijack** [comment]
Support DNS discover feature now. But I have no Amazon EC2s, so I cannot test metadata auto fill, so I have not work on that part, please check.

**Comment by keijack** [comment]
I close this issue for the feature is done, If help is needed, please submit another issue.
