### ISSUE TITLE
Use an async http client lib

### ISSUE THREAD

**Issue by tuttleBen** [keijack/python-eureka-client#4]
I would like to use aiohttp for making http calls. Either having a way to extract out the network location or a way to inject my own function to make the http call. However, the do_service would need to be async to make it work.

**Comment by keijack** [comment]
I have add a `walk_nodes` function, and also provide a `async` version, please upgrade to v0.4.0 to use it. You can read the document to find out how to use it. If you have any questions, you can comment this issue or send me email `keijack.wu@gmail.com`, enjoy.
