### ISSUE TITLE
Exception in discovery only mode

### ISSUE THREAD

**Issue by peter254** [keijack/python-eureka-client#40]
When using the init method in discovery-mode only, then there is an exception.
Code to execute:
`eureka_client.init(eureka_server='https://...', should_register=False, instance_host='something')`

Exception:
Attribute Error: 'EurekaClient' object has no attribute '_EurekaClient__instance_host'

I think I have found the reason:
In file eureka_client.py, line 959 the attribute `instance_host` is accessed, but when `should_register=False` then the attribute is never set.

If instance_host is not set, then it fails one line earlier with the same message.

**Comment by keijack** [comment]
Fixed, please upgrade to v0.8.7.

**Comment by keijack** [comment]
@peter254 I'm closing this, if you have any problem, start a new issue.

**Comment by peter254** [comment]
Thank you for the quick fix!! Awesome!
