### ISSUE TITLE
There is a way to catch failed heartbeats?

### ISSUE THREAD

**Issue by brenramz** [keijack/python-eureka-client#42]
There is a way to catch failed heartbeats when all servers are down? As I see in the documentation urllib HTTPError can raise it on do_service, but I'm getting 'NoneType' object has no attribute 'get_application'

**Comment by keijack** [comment]
It seems not only the heartbeat failed, the whole Registry was not pulled in your case? Could you show me some logs?

**Comment by brenramz** [comment]
Well I figure out was the error, the resourse was  not available, other process erase it, but I still having the problem when eureka.init() cant not connect, because eureka server is down, I can't catch the error, just get a lot of exceptions like every 30 seconds.

![image](https://user-images.githubusercontent.com/50213716/101221296-063d6280-364d-11eb-8a4b-58753751c60e.png)


![image](https://user-images.githubusercontent.com/50213716/101221433-4b619480-364d-11eb-8eb5-f55a0e7d2999.png)

**Comment by brenramz** [comment]
I'm using

```
eureka_client.init(
    eureka_server=eureka._ervers,
    app_name=app_name,
    instance_port=instance_port,
    instance_host=instance_host
)
```

**Comment by keijack** [comment]
It seems there is a Timeout when visiting your eureka server, could you please use `curl [your eureka server]` in your machine to check if you can reach the registry server.

**Comment by keijack** [comment]
For no response for a week, I close this. If you have any problem, please submit anther issue.
