### ISSUE TITLE
Pip install v0.8.10 failing

### ISSUE THREAD

**Issue by reecemetcalfe** [keijack/python-eureka-client#45]
Hi,

I'm stuck on Python 2.7 working with a legacy codebase and getting the following error when trying to pip install the last supported version. I've upgraded pip and setuptools. Any ideas?

$ pip install py_eureka_client==0.8.10
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting py_eureka_client==0.8.10
  Using cached py_eureka_client-0.8.10.tar.gz (30 kB)
    ERROR: Command errored out with exit status 1:
     command: /var/ctp/ctp_envs/rmetcalfe/4d04e38328c4745b/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1bzfkg/py-eureka-client/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1bzfkg/py-eureka-client/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-MrZ56m
         cwd: /tmp/pip-install-1bzfkg/py-eureka-client/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1bzfkg/py-eureka-client/setup.py", line 8, in <module>
        ver = os.environ["py_eureka_client_version"]
      File "/var/ctp/ctp_envs/rmetcalfe/4d04e38328c4745b/lib/python2.7/UserDict.py", line 40, in __getitem__
        raise KeyError(key)
    KeyError: 'py_eureka_client_version'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Thanks

**Comment by keijack** [comment]
Oh, please use 0.8.12, thank you

**Comment by reecemetcalfe** [comment]
All good now, thank you!
