### ISSUE TITLE
Remove dependency to netifaces to make Windows usecases easier

### ISSUE THREAD

**Issue by uwohlfeil** [keijack/python-eureka-client#46]
The library netifaces requires `Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio` on windows.
As far as I understand the code, this library is only used in one  function [get_first_non_loopback_ip](https://github.com/keijack/python-eureka-client/blob/c9cd7ffbe1746182012907c7329ad396373d21a5/py_eureka_client/netint_utils.py#L49).

Is it possible to replace this library another one like [pydron/ifaddr](https://github.com/pydron/ifaddr)?

```python
import ipaddress
import ifaddr

network = "192.168.178.0/24"

adapters = ifaddr.get_adapters()


def get_first_non_loopback_ip(network: str = "") -> str:
    for adapter in adapters:
        for iface in adapter.ips:
            if iface.is_IPv4:
                _ip = iface.ip
                if network:
                    if ipaddress.ip_address(_ip) in ipaddress.ip_network(network):
                        return _ip
                elif _ip != "127.0.0.1":
                    return _ip
    return ""


print(get_first_non_loopback_ip(network))
```

This library works at least in my case under Linux and Windows without any installation problem.
Both libraries seems to have the same license (MIT).

**Comment by keijack** [comment]
Thank you for your code, I've merge you PR, and release a new version 0.9.5.

**Comment by keijack** [comment]
Thank you for you code again, I close this, if you have any other problem, please submit another issue.
