### ISSUE TITLE
Why was version 0.8.10 deleted from pypi?

### ISSUE THREAD

**Issue by peter254** [keijack/python-eureka-client#49]
Hello,
we are currently using version 0.8.10 and it was deleted from pypi. We have a complicated process for updating libraries, so I would like to understand why it was deleted to determine whether we need to update.

**Comment by keijack** [comment]
I am sorry about that.

In fact, I want to delete all the versions that support python2 but only keep the newest version 0.8.12. 

And 0.8.12 is only made to fix this #45 . The only change of this is not to read the version from the system environment. And if you are using 0.8.10, it works fine and does not need to be updated.

**Comment by keijack** [comment]
I'm closing this issue, if you have any other problem, please submit another issue, thanks. And sorry for the trouble by the deletion.
