### ISSUE TITLE
Bug - get_applications from eureka server registry

### ISSUE THREAD

**Issue by dinuta** [keijack/python-eureka-client#51]
Hi @keijack ,

I discovered a bug in the client discovery. Version 0.9.6. Probably this is not new.

Steps to reproduce:
1. Spawn the environment from https://www.katacoda.com/dinuta/scenarios/estuary-discovery
2. You will reach a step where eureka server is deployed and can be accessed via browser via a public address. 
 The address has the form:  https://2886795372-8080-frugo04.environments.katacoda.com/eureka/ Here you will see the services registered.
3. List the apps from the eureka server registry: Example: https://2886795372-8080-frugo04.environments.katacoda.com/eureka/v2/apps. In the xml sent by eureka you will see 3 Agents.
4. Get the same list with the eureka client implemented on your side which points to the public eureka address. The registration address has the form:  https://2886795372-8080-frugo04.environments.katacoda.com/eureka/v2. It will only see just 1 Agent.

Expected behavior: The client sees 3 Agents and 1 discovery
Actual result: The client sees 1 Agent and 1 discovery

Please have a look.

Thanks,
Catalin

**Comment by keijack** [comment]
Thanks for submitting, I'll check it out later for the network connection now in my city is poor during this period.

**Comment by dinuta** [comment]
It seems like the InstanceId was '' for all the services. I saw you use this info in your code to uniquely identify the application. In this case your lib override the previous entry because of that. 

If it does make sense to have InstanceId same (but think not) it is a bug, otherwise not.

This is the fix in the agent: https://github.com/estuaryoss/estuary-agent-go/pull/5/files

I let the environment replicate the bug if you still need to debug it.

Thanks,
Catalin

**Comment by dinuta** [comment]
I closed the issue, thanks.

**Comment by keijack** [comment]
I think you should give each your instance an unique ID. However, it seems that sometimes the eureka server accepts the empty instance ids. I change some code, if the instance have no id get from eureka server, one will be generated via host name, ip address, app name and instance port. You can find the change in 0.9.7.
