### ISSUE TITLE
AttributeError: 'Timer' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by uwohlfeil** [keijack/python-eureka-client#53]
With Python 3.9.5 I geht the following error:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/uw/development/python_enaio_metrics/env/lib/python3.9/site-packages/py_eureka_client/eureka_client.py", line 1712, in _cleanup_before_exist
    cli.stop()
  File "/home/uw/development/python_enaio_metrics/env/lib/python3.9/site-packages/py_eureka_client/eureka_client.py", line 1534, in stop
    if self.__heartbeat_timer.isAlive():
AttributeError: 'Timer' object has no attribute 'isAlive'
```

The problematic line (eureka_client.py:1534) is:
```python
    def stop(self) -> None:
        if self.__heartbeat_timer.isAlive():
```
It seems to be related to [Python Issue 37804](https://bugs.python.org/issue37804).

If I change the line to:
```python
    def stop(self) -> None:
        if self.__heartbeat_timer.is_alive():
```
Everything seems to work.
The method is_alive seems to exists at lease since [python 2.7](https://docs.python.org/2.7/library/threading.html) and [python 3.5](https://docs.python.org/3.5/library/threading.html).

Can you change this to is_alive ?

**Comment by keijack** [comment]
Of course, please check out version 0.9.10

**Comment by keijack** [comment]
I close this, if you have any problem, please re-open it, thanks for submitting.
