### ISSUE TITLE
about eureka down questions

### ISSUE THREAD

**Issue by Yhmmmm** [keijack/python-eureka-client#56]
I use py_eureka_client in flask and register service to eureka, then to send heratbeat, but for some time, eureka_client raise Exception  [ py_eureka_client.eureka_client.EurekaServerConnectionException: <urlopen error All eureka servers in all zone are down!> ], and eureka lost the service.
I always use callback method to stop eureka_client and restart init, bug remind me eureka_client is running, i dont what i should do
![image](https://user-images.githubusercontent.com/33576253/123937723-0a561680-d9c9-11eb-87ed-35620e6020fe.png)

**Comment by keijack** [comment]
This error means that the component cannot send heartbeat to your eureka server, that means that your eureka server goes down or the heartbeat url is not quite right.

**Comment by yuhuiming** [comment]
but i restart the server, its ok, for some time, then will down, i dont kown why

**Comment by keijack** [comment]
Did all the heartbeat connections not work? After you restarted your flask server, would the error occurr in 30 seconds?

**Comment by keijack** [comment]
Did all the heartbeat connections not work? After you restarted your flask server, would the error occur in 30 seconds?

**Comment by yuhuiming** [comment]
i want kown the eureka link address what should i used, i think there is something wrong with the link address
