### ISSUE TITLE
about gunicorn

### ISSUE THREAD

**Issue by winxblast** [keijack/python-eureka-client#6]
兄弟，感觉你是中国的，我就直接写中文了
我在直接启动 flask 的情况下，能把 python 顺利注册到本地的注册中心。
然后在服务器上使用 gunicorn 启动 flask ，就无法正常启动应用了，错误日志在公司电脑，没法拷贝出来···
请问能支持 gunicorn 启动么？多 worker 情况呢？

**Comment by keijack** [comment]
I have not tested it in gunicorn, I will give it a try and find some solution for you.

**Comment by winxblast** [comment]
thanks
now I decide to use the spring-cloud-netflix-sidecar to register python web service to the eureka

**Comment by keijack** [comment]
I see, sidecar is always a fallback option.

**Comment by hyytt** [comment]
你好，我用的是0.0.2这个版本的包，遇到一个问题，就是正式环境下，将Python服务注册到eureka上以后，开始运行一天就从eureka上掉了，但是服务没挂。后来重新安装了一下包，隔了一周又掉了，但是服务没挂。测试环境测的时候就一直在eureka上，修改日志输出也可以看到一直有发送心跳。正式环境和测试环境可能的区别就是正式环境一直有别人在掉它的接口，测试环境没有人调它的接口。想咨询一下可能会是什么问题呢

**Comment by keijack** [comment]
@hyytt I'm so sorry that I response so late, I want some more information, is the heartbeat success?

**Comment by hyytt** [comment]
我们是在flask框架中使用的。最近在日志中打印看了一下，好像在服务运行中要是从eureka上掉了，以后的重试都不会成功，都会说eureka的节点是down的，也可能是我们某个接口有问题，我起了两个一样的服务，但是这两个服务的调用服务是不一样的，调用的接口也不一样。一个是一直能正常发送心跳的，另一个是失败一次以后，重试都不成功。哈哈，大神的源码我也看了几遍，也没找到原因呢，不过我们这个项目不是很着急，所以可以慢慢测试。目前还在测试中。。。。。。。。。。。。

**Comment by hyytt** [comment]
你好，这个问题我们找到了，是我们自己的服务有点问题。但是有个地方还是有点疑问，就是在运行过程中如果服务已经从eureka上掉线以后，再发送心跳失败几次后是不是应该尝试重新注册呢，因为eureka上已经没有这个服务的注册信息，再不停的发送心跳已经没有意义了。我们目前是修改了此处的逻辑。

**Comment by keijack** [comment]
@hyytt in the latest version, it will try to register when hearbeat fails:

```python
    def send_heart_beat(self, overridden_status=""):
        try:
            self.__try_all_eureka_server(lambda url: send_heart_beat(url, self.__instance["app"],
                                                                     self.__instance["instanceId"], self.__instance["lastDirtyTimestamp"],
                                                                     status=self.__instance["status"], overriddenstatus=overridden_status))
        except:
            _logger.exception("Error!")
            _logger.info("Cannot send heartbeat to server, try to register")
            self.register()
```
