### ISSUE TITLE
When the third-party service changes the IP address and re registers, the client cannot update the cache

### ISSUE THREAD

**Issue by wanxiang110** [keijack/python-eureka-client#61]
One: When the third-party service changes the IP address and re registers, the client cannot update the applications cache. Can you add functions?

Two: for python 3.7+          647: return self.__eureka_availability_zones.keys()[0]    error：TypeError: 'dict_keys' object is not subscriptable

**Comment by keijack** [comment]
1. The cache will be updated in next heartbeat, for the mechanical of the eureka, the registry will only be pulled by the client, but not pushed by the server. And It's not efficient to pull the registry in every service call. If you want to update the registry more frequently, you can set `renewal_interval_in_secs` smaller, which is set to 30 seconds by default. 

2. This is a bug and it's fixed now in 0.10.4.
