### ISSUE TITLE
0.11.6 breaking - missing dependencies 

### ISSUE THREAD

**Issue by bowman-david** [keijack/python-eureka-client#74]
During pip installation of the latest py-eureka-client (0.11.6), error message complains about missing ifaddr dependency:

`ModuleNotFoundError: No module named 'ifaddr'`

**Comment by keijack** [comment]
What version of pip do you use?

**Comment by bowman-david** [comment]
@keijack 

I have replicated this on Windows 10 + Python 3.9 with `pip 21.2.3` and `pip 22.3.1` and took a few minutes to write out my replication steps, in case my original comment was a little unclear/sparse. 

**Reproduction Steps:**
1.  Wipe your installed modules:
```
pip freeze > existinginstalls.txt 
pip uninstall -r existinginstalls.txt -y
```

2. `pip` install the project with the `py-eureka-client` dependency. 
```
pip install -r requirements.txt 
```

3.  Run a script or module that imports `py-eureka-client`  (in this case, the actual running app is a FastAPI app with Uvicorn) -- some user/app/path/module name sanitization below. 
```
File "C:\mypath\.\src\main.py", line 7, in <module>
    from mymodule import eureka_registration
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\mymodule\eureka_registration.py", line 5, in <module>
    import py_eureka_client.eureka_client as eureka
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\py_eureka_client\eureka_client.py", line 42, in <module>
    import py_eureka_client.netint_utils as netint
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\py_eureka_client\netint_utils.py", line 26, in <module>
    from ifaddr import get_adapters
ModuleNotFoundError: No module named 'ifaddr'
```

**Comment by keijack** [comment]
Please use 0.11.7

**Comment by bowman-david** [comment]
Thank you, @keijack!  Will pull and test this out tomorrow!
