### ISSUE TITLE
422 Unprocessable Entity when using do_service_async

### ISSUE THREAD

**Issue by ahbe** [keijack/python-eureka-client#79]
When using do_service_async to communicate a POST call to another service that requires a JSON data I always get a 422 Unpro cessable Entity error 

`data = {"image":"path_image_str"}`

    try:
        res = await eureka_client.do_service_async("app_name", "/api_path",method="POST",data=data,headers={"Authorization": 'Bearer ' + token})
    except urllib.request.HTTPError as e:
        print(e) 

I've tried using json.dumps but it yield another error :  res was used before being assigned

**Comment by keijack** [comment]
If json.dumps doesn't work, please check your server side logic. And please check whether your server side accept `application/json` data but not `application/x-www-form-urlencoded`

**Comment by keijack** [comment]
Close for long time silence. If you have any problem, please submit a new one.
