### ISSUE TITLE
0.11.9 failover link is skipped

### ISSUE THREAD

**Issue by tcmorar** [keijack/python-eureka-client#80]
In case of URLError(TimeoutError('timed out')) for the first eureka server, the exception is not caught so there is not try to connect to the second eureka server. It looks that the http_client.URLError is not seen as the urllib.error.URLError (line 633).

Second problem is that applications() method which calls __pull_full_registry() which is async method and it is not awaited (eureka_client.py line 559) which means it only creates coroutine but it can remain unexecuted. The logged error is:
...\pyicom\venv\Lib\site-packages\py_eureka_client\eureka_client.py:559: RuntimeWarning: coroutine 'EurekaClient.__pull_full_registry' was never awaited
  self.__pull_full_registry()

**Comment by tcmorar** [comment]
Possible fix (I tested it and it works fine):
![image](https://github.com/keijack/python-eureka-client/assets/145466834/30bee011-7a66-4a70-b302-c8f294589c72)

**Comment by keijack** [comment]
Fix in `0.11.10`, please check

**Comment by tcmorar** [comment]
Indeed the problem is solved in 0.11.10. Thanks for the fast reply.
