### ISSUE TITLE
How can I alter the heartbeat of the instance

### ISSUE THREAD

**Issue by PFernandezTorres** [keijack/python-eureka-client#81]
In my spring boot project, I have set that every client needs to send every 5s a heartbeat and an expiration time of 9s. If the python instance has set per default a 30s heartbeat, it can lead to errors. How I can alter the python settings so it is the same at its spring boot peers

**Comment by keijack** [comment]
You can set `renewal_interval_in_secs` in the `init` function to change the `heartbeat` interval.

**Comment by PFernandezTorres** [comment]
Thank you. I didn't see that property in the docs
