### ISSUE TITLE
Applications.get_application method is case-sensitive

### ISSUE THREAD

**Issue by josephgrigg** [keijack/python-eureka-client#89]
`get_application` seems like it was written to be case insensitive, but it requires uppercase for the app_name. Referring to this method: https://github.com/keijack/python-eureka-client/blob/8b78a366721fa075192434cd71cbd04169a24c49/py_eureka_client/eureka_basic.py#L244-L250

The `__application_name_dic` stores app names in uppercase. It seems like the if-condition should be updated to:

```python
            aname = app_name.upper()
            if aname in self.__application_name_dic:
                return self.__application_name_dic[aname]
```

**Comment by keijack** [comment]
Yes, you are right. The bug is fix now.
